# The Docker image that will be used to build your app
image: node:18
# Functions that should be executed before the build script is run

pages:
    stage: deploy
    environment: production
    before_script:
        - npm -v
    script:
        - echo "开始执行脚本"
        - npm i 
        - npm run build
    artifacts:
        paths:
            - public
