# The Docker image that will be used to build your app
image: ccr.ccs.tencentyun.com/linux_environment/debian:1.0.0
# Functions that should be executed before the build script is run

pages:
    stage: deploy
    environment: production
    script:
        - echo "开始执行脚本"
        - pnpm i 
        - pnpm run build
    artifacts:
        paths:
            - public
